### ISSUE TITLE
Weapons in Weapon Master Mod don't consume stamina correctly

### ISSUE THREAD

**Issue by gulatan** [orlouge/unruffled#1]
It consumes a little stamina, but the balance is not the same as that of a vanilla weapon, and the config doesn't seem to be applied.

**Comment by orlouge** [comment]
I haven't tried the mod. Do those weapons have a very high attack speed (above 3)? If yes, it's intended behaviour, the stamina shouldn't prevent you from attacking quickly if the weapon allows it. If not, it might be a compatibility issue, but that mod is closed source so I'm not going investigate that.
